import os

Import('flags Libname Libhome OtherInc be')
allflags = " -Wall -Wunused -Wextra -Werror -Woverloaded-virtual -Wsign-promo "
allflags += " -Wno-uninitialized "
flags = flags + allflags


### make sure that BOOM2/src is part of include path
pwd = os.environ['PWD']
libpath= [os.path.join(pwd, 'src')] + OtherInc + be['incpath']


env = Environment(CC= be['CC'],
                  CXX=be['CXX'],
                  CCFLAGS = flags + '-L/home/stevescott/lib',
                  ARFLAGS = '-ru',
                  RANLIB = 'echo',
                  LIBPATH = libpath + ['/home/stevescott/lib'],
                  CPPPATH = libpath
                  )

Export('env')

sc_list = Split("""
Bmath
LinAlg
Models
Models/Policies
Models/PosteriorSamplers
Models/Glm
Models/Glm/PosteriorSamplers
Models/HMM
Models/HMM/PosteriorSamplers
Models/StateSpace
Models/StateSpace/Filters
Models/StateSpace/PosteriorSamplers
Models/IRT
Samplers
TargetFun
cpputil
distributions
numopt
stats
""")

## Models/TimeSeries  ## all headers.  See StateSpace



obj = []
for subdir in sc_list :
    o = SConscript('%s/SConscript' % subdir)
    obj += o

### Decider('MD5-timestamp')

thelib = env.Library(Libname, obj)
env.Precious(thelib)
env.Install(Libhome, thelib)
