Import('env')

file_list = Split("""
add_to_path.cpp
cat_string.cpp
check_empty.cpp
check_directory.cpp
compare_vector_bool.cpp
count_lines.cpp
Date.cpp
DateTime.cpp
DefaultVnames.cpp
get_date.cpp
get_dpath.cpp
gll.cpp
io.cpp
io_manager.cpp
infinity.cpp
is_numeric.cpp
is_all_white.cpp
legalize_file_name.cpp
LongString.cpp
lse.cpp
mkdir.cpp
OutputTable.cpp
parse_range.cpp
ParamHolder.cpp
ProgramOptions.cpp
ProgressTracker.cpp
print_columns.cpp
Redirector.cpp
replace_all.cpp
read_file.cpp
rep.cpp
report_error.cpp
safelog.cpp
split.cpp
split_delimited.cpp
split_string.cpp
str2d.cpp
strip.cpp
strip_path.cpp
strip_white_space.cpp
trim_white_space.cpp
""")

## REMOVED
# DataTable.cpp
# Resampler.cpp
# include.cpp
# pwd.cpp
# simple_random_sample.cpp

obj = env.Object(file_list)
Return('obj')
