Import('env')

file_list = Split("""
ChoiceData.cpp
Glm.cpp
GlmCoefs.cpp
GlmMvnPrior.cpp
MvnGivenX.cpp
MvnGivenXandSigma.cpp
RegressionModel.cpp
WeightedRegressionModel.cpp
TRegression.cpp
LogisticRegressionModel.cpp
ProbitRegression.cpp
OrdinalCutpointModel.cpp
CumulativeLogitModel.cpp
CumulativeProbitModel.cpp
MultinomialLogitModel.cpp
MLogitBase.cpp
MLogitSplit.cpp
MultinomialProbitModel.cpp
MvReg2.cpp
MvtRegModel.cpp
VariableSelectionPrior.cpp
""")

obj =env.Object(file_list)
Return('obj')


