Import('env')

## ConditionalMarkovModel.cpp

file_list = Split("""
HomogeneousStateModel.cpp
LocalLinearTrend.cpp
ScalarHomogeneousStateSpaceModel.cpp
""")

## SeasonalStateModel.cpp

obj =env.Object(file_list)
Return('obj')
