Import('env')

file_list = Split("""
IRT.cpp
Item.cpp	
Subject.cpp
IrtModel.cpp
PartialCreditModel.cpp
DafePcrDataImputer.cpp
DafePcrItemSampler.cpp
DafePcrRwmItemSampler.cpp
DafePcrRwmSubject.cpp
DafePcrSubject.cpp
SubjectPrior.cpp
SubjectSliceSampler.cpp
""")

obj =env.Object(file_list)
Return('obj')
